'use client';
import React,{useId,useState} from 'react';
import {Button as PrimitiveButton} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Badge as PrimitiveBadge} from '@/components/ui/badge';
import {Avatar,AvatarFallback} from '@/components/ui/avatar';
import {Tooltip,TooltipTrigger,TooltipContent} from '@/components/ui/tooltip';
import {Alert,AlertTitle,AlertDescription} from '@/components/ui/alert';
import {Loader2,Eye,EyeOff,Search,CheckCircle2,AlertCircle,Info,TriangleAlert,Copy,Check} from 'lucide-react';
import {toast} from 'sonner';
export type Tone='neutral'|'success'|'warning'|'danger'|'info';
export function BrandMark({className=''}:{className?:string}){return <svg className={'brand-mark '+className} width="32" height="32" viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M18 6H6v20h16V14M12 3H3v26h13M23 6l7-4" stroke="currentColor" strokeWidth="1.8"/></svg>}
export function Button({kind='primary',busy=false,className='',children,...p}:React.ComponentProps<typeof PrimitiveButton>&{kind?:'primary'|'secondary'|'quiet'|'danger'|'accent';busy?:boolean}){return <PrimitiveButton {...p} disabled={p.disabled||busy} aria-busy={busy||undefined} variant={kind==='danger'?'destructive':kind==='quiet'?'ghost':kind==='secondary'?'outline':'default'} className={`adt-btn ${kind} ${className}`}>{p.asChild?children:<>{busy&&<Loader2 className="spin"/>}{children}</>}</PrimitiveButton>}
export function IconButton({label,children,...p}:React.ComponentProps<typeof Button>&{label:string}){return <Tooltip><TooltipTrigger asChild><Button kind="quiet" size="icon" aria-label={label} {...p}>{children}</Button></TooltipTrigger><TooltipContent>{label}</TooltipContent></Tooltip>}
export function Badge({children,tone='neutral',className=''}:{children:React.ReactNode;tone?:Tone;className?:string}){return <PrimitiveBadge variant="outline" className={`adt-badge ${tone} ${className}`}>{children}</PrimitiveBadge>}
export function PersonAvatar({name='Ana Moutinho',size='md'}:{name?:string;size?:'sm'|'md'|'lg'}){return <Avatar className={`person-avatar ${size}`} aria-label={name}><AvatarFallback>{name.split(' ').slice(0,2).map(n=>n[0]).join('')}</AvatarFallback></Avatar>}
export function AvatarGroup({names=['Ana Moutinho','Rafael Costa','Luiza Reis'],extra=2}:{names?:string[];extra?:number}){return <div className="avatar-group">{names.map(n=><PersonAvatar key={n} name={n} size="sm"/>)}{extra>0&&<span className="avatar-extra" aria-label={`Mais ${extra} membros`}>+{extra}</span>}</div>}
export function Field({label,hint,error,type='text',multiline=false,className='',...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string;hint?:string;error?:string;multiline?:boolean}){const id=useId();const [show,setShow]=useState(false);return <div className={`field ${error?'invalid':''} ${className}`}><label htmlFor={id}>{label}</label><div className={`input-wrap ${type==='search'?'with-icon':''}`}>{type==='search'&&<Search/>}{multiline?<Textarea {...(props as unknown as React.TextareaHTMLAttributes<HTMLTextAreaElement>)} id={id} aria-invalid={!!error} aria-describedby={hint||error?id+'-help':undefined} placeholder={props.placeholder} disabled={props.disabled} defaultValue={props.defaultValue as string} className="adt-input"/>:<Input {...props} id={id} type={type==='password'&&show?'text':type} aria-invalid={!!error} aria-describedby={hint||error?id+'-help':undefined} className="adt-input"/>}{type==='password'&&<IconButton className="password-toggle" label={show?'Ocultar senha':'Mostrar senha'} onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</IconButton>}</div>{(hint||error)&&<p id={id+'-help'} className={error?'field-error':'field-hint'}>{error&&<AlertCircle/>}{error||hint}</p>}</div>}
export function Notice({tone='info',title,children}:{tone?:Tone;title:string;children?:React.ReactNode}){const Icon=tone==='success'?CheckCircle2:tone==='danger'?AlertCircle:tone==='warning'?TriangleAlert:Info;return <Alert className={`notice ${tone}`}><Icon/><AlertTitle>{title}</AlertTitle>{children&&<AlertDescription>{children}</AlertDescription>}</Alert>}
export async function copyText(text:string){try{await navigator.clipboard.writeText(text);toast.success('Copiado para a área de transferência.');return true;}catch{toast.error('Não foi possível copiar. Selecione o texto e copie manualmente.');return false;}}
export function CopyButton({text,label='Copiar'}:{text:string;label?:string}){const[copied,setCopied]=useState(false);return <IconButton label={copied?'Copiado':label} onClick={async()=>{if(await copyText(text)){setCopied(true);setTimeout(()=>setCopied(false),1800)}}}>{copied?<Check/>:<Copy/>}</IconButton>}
export function Specimen({id,title,description,tag,children,wide=false}:{id:string;title:string;description:string;tag?:string;children:React.ReactNode;wide?:boolean}){return <article id={id} className={`specimen ${wide?'wide':''}`}><header className="specimen-head"><div><h3>{title}</h3><p>{description}</p></div>{tag&&<code>{tag}</code>}</header><div className="specimen-body">{children}</div></article>}
export function Variant({label,children}:{label:string;children:React.ReactNode}){return <div className="variant"><span className="eyebrow">{label}</span>{children}</div>}
