'use client';
import {tokens} from './tokens';
import {Specimen,Variant,copyText} from './core';
import {ArrowUpRight,Search,Plus,Check,Paperclip,MessageSquare,Folder,Settings,Image,BookOpen,Command,SlidersHorizontal,Copy,Trash2,Download,CheckCircle2} from 'lucide-react';
const colors=[['primary','Verde profundo','Ações e identidade'],['background','Marfim','Fundo da página'],['surface','Papel','Superfícies'],['sage','Sálvia','Apoio visual'],['accent','Manteiga','Destaques'],['terracotta','Terracota','Detalhes']] as const;
export function Foundations(){return <div className="catalog-grid">
<Specimen id="cores" title="Paleta da marca" description="Uma base acolhedora. Contraste para dar direção." tag="color.*" wide><div className="color-grid">{colors.map(([key,name,use])=><button className="color-item" key={key} onClick={()=>copyText(tokens.color[key])} aria-label={`Copiar ${name}: ${tokens.color[key]}`}><span className={'color-chip '+key} style={{background:tokens.color[key]}}><Copy size={16}/></span><strong>{name}</strong><code>{tokens.color[key]}</code><small>{use}</small></button>)}</div><div className="spec-note"><Copy size={14}/>Clique em uma cor para copiar seu código.</div></Specimen>
<Specimen id="tipografia" title="Tipografia" description="Personalidade nos títulos. Clareza em cada leitura." tag="font.*" wide><div className="type-layout"><div className="type-hero"><span className="eyebrow">PLAYFAIR DISPLAY · TÍTULOS</span><div className="big-aa">Aa<span>&</span></div><h4>Clareza para<br/><em>ir além.</em></h4></div><div className="type-scale">{[['Título principal','Aprender. Aplicar. Avançar.','32 / 1.2','type-h'],['Subtítulo','Seu próximo passo começa aqui.','24 / 1.3','type-sub'],['Texto · Inter','Seu conhecimento merece chegar mais longe.','16 / 1.6','type-body'],['Rótulo · Inter Medium','Nome do projeto','14 / 1.4','type-label'],['Legenda · Inter','Atualizado há 5 minutos','12 / 1.5','type-caption'],['Código · IBM Plex Mono','const proximoPasso = "aplicar";','14 / 1.6','type-code']].map(([label,text,size,cls])=><div className="type-row" key={label}><div><span className="eyebrow">{label}</span><p className={cls}>{text}</p></div><code>{size}</code></div>)}</div></div></Specimen>
<Specimen id="semantica" title="Cores semânticas" description="Cada cor tem uma função, acompanhada de texto ou ícone." tag="color.*"><div className="token-list">{[['ink','Texto principal'],['muted','Texto secundário'],['border','Divisores'],['controlBorder','Bordas de campos'],['focus','Foco de teclado'],['primaryHover','Ação em hover'],['disabled','Superfície desabilitada'],['disabledText','Texto desabilitado'],['success','Sucesso'],['warning','Atenção'],['danger','Erro'],['info','Informação']].map(([key,label])=><button key={key} onClick={()=>copyText(tokens.color[key as keyof typeof tokens.color])}><span className="token-dot" style={{background:tokens.color[key as keyof typeof tokens.color]}}/><span>{label}</span><code>{tokens.color[key as keyof typeof tokens.color]}</code></button>)}</div></Specimen>
<Specimen id="espacamento" title="Espaçamento" description="Ritmo consistente, baseado em múltiplos de 4 px." tag="space.*"><div className="spacing-list">{tokens.space.map(n=><div key={n}><code>space-{n}</code><span style={{width:n*3}}/><small>{n} px</small></div>)}</div></Specimen>
<Specimen id="bordas" title="Bordas e elevação" description="Contornos leves. Profundidade apenas quando necessária." tag="radius · shadow"><div className="radii">{Object.entries(tokens.radius).map(([key,n])=><div key={key}><span style={{borderRadius:n}}/><code>{n===999?'pill':n+'px'}</code></div>)}</div><div className="shadows">{Object.entries(tokens.shadow).map(([key,shadow])=><div key={key} style={{boxShadow:shadow}}><span>{key==='small'?'Baixa':key==='medium'?'Média':'Alta'}</span></div>)}</div><p className="muted">Campos: 8 px · Cards: 12 px · Painéis: 16 px<br/>Borda: 1 px · Anel de foco: 3 px</p></Specimen>
<Specimen id="icones" title="Iconografia" description="Lucide: traço de 1,5 px, cantos suaves e formas simples." tag="icon.*"><div className="icon-grid">{[Search,Plus,ArrowUpRight,Check,Paperclip,MessageSquare,Folder,Settings,Image,BookOpen,Command,SlidersHorizontal,Copy,Trash2,Download,CheckCircle2].map((Icon,i)=><div key={i}><Icon size={24} strokeWidth={1.5}/></div>)}</div><div className="row"><Variant label="16 PX"><Search size={16}/></Variant><Variant label="20 PX"><Search size={20}/></Variant><Variant label="24 PX"><Search size={24}/></Variant></div><p className="muted">Botões só com ícone recebem nome acessível e tooltip.</p></Specimen>
<Specimen id="principios" title="Aplicação e acessibilidade" description="As mesmas regras orientam cada peça." wide><div className="principles"><div><strong>01 / Hierarquia</strong><p>Títulos editoriais, controles objetivos e uma ação principal por contexto.</p></div><div><strong>02 / Leitura</strong><p>Texto em 16 px, rótulos em 14 px. Marfim sobre verde; texto escuro sobre amarelo.</p></div><div><strong>03 / Movimento</strong><p>Transições de 150–220 ms. Animações reduzidas conforme a preferência do dispositivo.</p></div><div><strong>04 / Referência</strong><p>A hierarquia da referência pública do <a href="https://onovomercado.com/" target="_blank" rel="noreferrer">Novo Mercado</a> encontra a paleta e a tipografia próprias do Além da Técnica.</p></div></div></Specimen>
</div>}
