'use client';
import {useState} from 'react';
import {Download,ArrowUpRight,Check,ArrowRight,PenLine,BookOpen,MessageCircle,CalendarCheck,ChartNoAxesCombined,Monitor,Smartphone,Copy} from 'lucide-react';
import {Button,Field} from '@/components/adt/core';
import {TooltipProvider} from '@/components/ui/tooltip';
import {Brand,Action,Eyebrow,RotatingPhrase} from '@/components/landing/design';
import {system,systemVariables,exportSystem} from '@/components/landing/system';
import '@/components/landing/horizon.css';
import './system.css';
export default function DesignSystem(){
 const[copied,setCopied]=useState(''),[width,setWidth]=useState(390),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function copy(value:string){try{await navigator.clipboard.writeText(value);setCopied(value);setMessage(`Copiado: ${value}`)}catch{setMessage(`Selecione e copie o valor: ${value}`)}}
 return <TooltipProvider><div className="adt-next ds-page" style={systemVariables}><header className="ds-header"><Brand/><nav aria-label="Catálogo"><a href="#fundamentos">Fundamentos</a><a href="#componentes">Componentes</a><a href="#movimento">Movimento</a><a href="#aplicacao">Aplicação</a></nav><a href="/">Ver landing page<ArrowUpRight size={17}/></a></header>
 <main className="hz-container"><section className="ds-intro"><Eyebrow>DESIGN SYSTEM · HORIZONTE / 02</Eyebrow><h1>Espaço para<br/><span>o que vem depois.</span></h1><div className="ds-intro-bottom"><p>Uma linguagem visual para apresentar o trabalho, facilitar a descoberta e transformar aprendizado em ação.</p><Button className="hz-action" onClick={exportSystem}><Download size={17}/>Exportar tokens</Button></div></section>
 <section className="ds-section" id="fundamentos"><div className="ds-heading"><Eyebrow number="01">FUNDAMENTOS</Eyebrow><h2>Clareza como ponto de partida.</h2></div><div className="ds-swatches">{Object.entries(system.color).map(([name,value])=><button key={name} onClick={()=>copy(value)} className="ds-swatch" aria-label={`Copiar ${name}: ${value}`}><span className="ds-color" style={{background:value}}/><span><strong>{name}</strong><code>{value}</code>{copied===value?<Check size={14}/>:<Copy size={14}/>}</span></button>)}</div><div className="ds-foundations-grid"><article><span className="ds-label">TIPOGRAFIA</span><div className="ds-aa">Aa</div><h3>Helvetica Neue</h3><p>Helvetica → Inter local → Arial. Uma família sem serifa, com títulos leves, espaçamento compacto e textos com respiro. Helvetica Now, identificada na referência, não é distribuída neste projeto.</p><div className="ds-type"><span className="ds-type-display">O próximo capítulo.</span><span className="ds-type-title">Seu trabalho tem valor.</span><p>Conhecimento que encontra a vida real.</p><small>Rótulos 14 px · Legendas 12 px · Corpo 16 px</small></div></article><article><span className="ds-label">ESPAÇO, FORMA E ÍCONES</span><div className="ds-spacing">{system.space.map(v=><div key={v}><span style={{width:v}}/><code>{v}</code></div>)}</div><div className="ds-radii">{Object.entries(system.radius).map(([k,v])=><div key={k}><span style={{borderRadius:v}}/><code>{k} · {v}</code></div>)}</div><div className="ds-icons">{[ArrowRight,PenLine,BookOpen,MessageCircle,CalendarCheck,ChartNoAxesCombined].map((Icon,i)=><Icon key={i} size={22} strokeWidth={1.5}/>)}</div><p>Lucide · Traço de 1,5 px · 16, 20 e 24 px.</p></article></div></section>
 <section className="ds-section" id="componentes"><div className="ds-heading"><Eyebrow number="02">COMPONENTES</Eyebrow><h2>Peças com a mesma intenção.</h2></div><div className="ds-component-grid"><article className="ds-demo"><span className="ds-label">AÇÕES · PADRÃO, HOVER, FOCO, DESABILITADO E CARREGANDO</span><div className="ds-button-row"><Action href="#aplicacao">Conhecer o projeto</Action><Action secondary href="#aplicacao">Experimentar</Action><Button kind="quiet" onClick={()=>setMessage('Ação discreta demonstrada.')}>Ação discreta<ArrowRight/></Button></div><div className="ds-button-row"><Button className="hz-action" disabled>Inscrições em breve</Button><Button className="hz-action" busy={busy} onClick={()=>{setBusy(true);setMessage('Demonstração em andamento.');setTimeout(()=>{setBusy(false);setMessage('Demonstração concluída.')},1400)}}>{busy?'Preparando…':'Testar carregamento'}</Button></div><p>52 px de altura · Raio pill · Pressão em 160 ms · Foco com contorno de 2 px.</p></article><article className="ds-demo"><span className="ds-label">CAMPOS · PADRÃO, ERRO E DESABILITADO</span><Field label="Qual serviço você oferece?" placeholder="Ex.: projetos de interiores"/><Field label="Para quem?" error="Informe o público que você atende." placeholder="Ex.: famílias que estão se mudando"/><Field label="Exemplo desabilitado" disabled value="Campo indisponível" readOnly/></article></div><div className="ds-feedback" role="status">{message||'Experimente os componentes. As interações desta página são demonstrações locais.'}</div></section>
 <section className="ds-section" id="movimento"><div className="ds-heading"><Eyebrow number="03">MOVIMENTO</Eyebrow><h2>Presença, sem interromper a leitura.</h2></div><div className="ds-motion-demo"><span>Seu talento merece</span><RotatingPhrase compact/></div><div className="ds-motion-rules"><div><strong>160–220 ms</strong><p>Respostas de botões e controles. Transições curtas de pressão, cor e foco.</p></div><div><strong>600–650 ms</strong><p>Entrada de seção e mudança de frase. Opacidade e deslocamento controlado.</p></div><div><strong>4 segundos</strong><p>Tempo entre as frases. Pausa manual, fora da tela e em abas inativas.</p></div></div><p className="ds-reduce-note">Com movimento reduzido, a troca automática para e os deslocamentos são removidos. A navegação, os exemplos e a seleção manual continuam disponíveis.</p></section>
 <section className="ds-section" id="aplicacao"><div className="ds-heading"><Eyebrow number="04">APLICAÇÃO</Eyebrow><h2>O sistema em contexto.</h2></div><div className="ds-preview-toolbar"><span>Landing page · Prévia funcional</span><div role="group" aria-label="Largura da prévia">{[{w:320,label:'320 px',Icon:Smartphone},{w:390,label:'390 px',Icon:Smartphone},{w:1000,label:'Desktop',Icon:Monitor}].map(({w,label,Icon})=><button key={w} aria-pressed={width===w} onClick={()=>setWidth(w)}><Icon size={15}/>{label}</button>)}</div><a href="/">Abrir página<ArrowUpRight size={15}/></a></div><div className="ds-preview-stage"><iframe title="Prévia responsiva da landing page" src="/" style={{width,maxWidth:'100%',height:780}}/></div></section></main><footer className="ds-footer hz-container"><span>Além da Técnica · Horizonte</span><a href="/biblioteca">Acessar biblioteca anterior<ArrowUpRight size={15}/></a></footer></div></TooltipProvider>;
}
