'use client';
import React,{useState} from 'react';
import {Accordion,AccordionContent,AccordionItem,AccordionTrigger} from '@/components/ui/accordion';
import {TooltipProvider} from '@/components/ui/tooltip';
import {ArrowDown,ArrowUpRight,Check,BookOpen,PenLine,MessageCircle,CalendarCheck,ChartNoAxesCombined,UserRound,Menu,X,Monitor,MoveUpRight} from 'lucide-react';
import {offer,checkoutWithAttribution} from './config';
import {Brand,Action,Eyebrow,Reveal,RotatingPhrase} from './design';
import {systemVariables} from './system';
import './horizon.css';
import {HeroArtwork} from './hero-artwork';
const applications=[
 {number:'01',Icon:UserRound,title:'Explique melhor o que você faz.',description:'Apresente seus serviços de um jeito que as pessoas entendam o valor do seu trabalho.',delivery:'Uma apresentação profissional mais clara.'},
 {number:'02',Icon:Monitor,title:'Organize sua presença digital.',description:'Ajude quem chega até você a entender seus serviços e encontrar o próximo passo.',delivery:'Um perfil com informações que fazem sentido.'},
 {number:'03',Icon:PenLine,title:'Tenha o que dizer nos seus conteúdos.',description:'Transforme dúvidas e situações do seu dia a dia em publicações úteis para o seu público.',delivery:'Uma publicação com assunto, mensagem e objetivo.'},
 {number:'04',Icon:MessageCircle,title:'Conduza melhor cada conversa.',description:'Responda com clareza, entenda a necessidade do cliente e facilite a continuidade do atendimento.',delivery:'Uma resposta de atendimento adaptada ao seu serviço.'},
 {number:'05',Icon:CalendarCheck,title:'Cuide das oportunidades de agendamento.',description:'Organize confirmações e lembretes para ajudar a reduzir esquecimentos e faltas.',delivery:'Um processo de confirmação de horários.'},
 {number:'06',Icon:ChartNoAxesCombined,title:'Entenda o que está dando resultado.',description:'Acompanhe contatos, agendamentos e vendas para decidir o que merece continuar ou mudar.',delivery:'Uma visão mais organizada dos resultados das ações.'},
];
const faqs=[
 ['Preciso saber marketing para acompanhar?','Não. O Além da Técnica foi pensado também para quem está começando do zero. As explicações partem de situações comuns da rotina profissional e mostram como transformar o aprendizado em uma ação concreta.'],
 ['O que vou encontrar no Além da Técnica?','Uma plataforma de desenvolvimento profissional com aulas simples, exemplos do dia a dia e atividades guiadas. Os temas envolvem apresentação de serviços, presença digital, conteúdo, atendimento, agendamento e acompanhamento de resultados.'],
 ['Isso serve para a minha profissão?','A proposta é ajudar profissionais que oferecem serviços ou cuidam do próprio negócio e precisam comunicar melhor o que fazem. Você adapta os exemplos ao seu público, ao seu atendimento e à realidade da sua área.'],
 ['Vou precisar passar o dia produzindo conteúdo?','A ideia é aprender a escolher ações que façam sentido para o seu negócio. Produção de conteúdo é uma parte do aprendizado; apresentação dos serviços, atendimento e acompanhamento das oportunidades também fazem parte.'],
 ['O projeto ensina a gerenciar campanhas de anúncios?','O foco desta proposta é organizar a presença profissional e melhorar a comunicação e o atendimento. Para gestão de tráfego e campanhas, conte com uma equipe especializada.'],
 ['Qual é o valor e como funciona o acesso?','A assinatura custa R$37 por mês. Após a confirmação do pagamento, você tem acesso imediato às aulas já gravadas na plataforma. Uma nova aula completa é liberada por semana.'],
 ['Já posso me inscrever?','Sim. As inscrições estão abertas. Clique em “Quero assinar” para concluir sua assinatura no checkout da Hotmart.'],
 ['O curso garante novos clientes ou aumento de faturamento?','Não há garantia de faturamento ou de quantidade de clientes. A plataforma ajuda você a tomar decisões melhores e a aplicar ações de marketing na sua realidade. Os resultados dependem da execução, do serviço, do público e do contexto de cada negócio.'],
];

export default function LandingPage(){
 const[menu,setMenu]=useState(false);
 const checkoutClick=(event:React.MouseEvent<HTMLAnchorElement>)=>{event.currentTarget.href=checkoutWithAttribution(offer.checkoutUrl)};
 return <TooltipProvider><div className="adt-next" style={systemVariables}>
 <a className="skip-link" href="#conteudo">Ir para o conteúdo</a>
 <header className="hz-header"><Brand/><nav className={`hz-nav ${menu?'open':''}`} aria-label="Navegação principal" id="navigation" onKeyDown={e=>{if(e.key==='Escape')setMenu(false)}}>{[['#como-funciona','O projeto'],['#aprendizado','O que você aprende'],['#duvidas','Dúvidas']].map(([href,label])=><a key={href} href={href} onClick={()=>setMenu(false)}><span>{label}</span></a>)}</nav><div className="hz-header-right"><Action href={offer.checkoutUrl} onClick={checkoutClick}>Quero assinar</Action><button type="button" className="hz-menu" aria-expanded={menu} aria-controls="navigation" aria-label={menu?'Fechar menu':'Abrir menu'} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 <main id="conteudo">
 <section className="hz-hero" id="inicio"><HeroArtwork/>
 <div className="hz-hero-content"><Eyebrow>DESENVOLVIMENTO PROFISSIONAL, NA PRÁTICA</Eyebrow><h1>Seu talento merece<span className="sr-only"> ser reconhecido.</span></h1><RotatingPhrase/><p className="hz-hero-description">Você já domina a sua profissão. Aprenda a apresentar seu trabalho, atrair clientes e cuidar de cada oportunidade.</p><div className="hz-hero-actions"><Action href={offer.checkoutUrl} onClick={checkoutClick}>Assinar por R$37/mês</Action><Action secondary href="#como-funciona">Entender a proposta</Action></div><div className="hz-hero-notes"><span><Check size={15}/>Comece do zero</span><span><Check size={15}/>Aprenda com exemplos</span><span><Check size={15}/>Aplique no seu negócio</span></div></div>
 <div className="hz-hero-bottom"><span>SUA PROFISSÃO É SÓ O COMEÇO.</span><a href="#como-funciona" aria-label="Explorar o projeto"><ArrowDown size={19}/></a><span aria-hidden="true"/></div></section>
 <section className="hz-intro hz-container hz-section" id="como-funciona"><Reveal><Eyebrow number="01">UM NOVO CAPÍTULO PROFISSIONAL</Eyebrow><div className="hz-intro-grid"><h2>Bom no que faz.<br/><span>Mais claro ao mostrar.</span></h2><div><p className="hz-lead">Entre saber fazer e ser escolhido, existe um caminho que a formação nem sempre ensina.</p><p>Como explicar o valor do seu serviço. O que publicar. Como responder a quem chega até você. O Além da Técnica ajuda a organizar essas decisões com aulas simples, exemplos e atividades guiadas.</p><a href="#aprendizado" className="hz-text-link">Veja o que você pode colocar em prática<ArrowUpRight size={18}/></a></div></div></Reveal>
 <div className="hz-principles">{[{n:'01',title:'Entenda.',text:'A explicação começa em uma situação que você já conhece.',icon:BookOpen},{n:'02',title:'Aplique.',text:'Adapte os exemplos ao seu serviço e saia com algo para usar.',icon:PenLine},{n:'03',title:'Avance.',text:'Observe o que funciona e decida o próximo passo com mais clareza.',icon:MoveUpRight}].map(item=><Reveal key={item.n}><article className="hz-principle"><div className="hz-principle-top"><span>{item.n} /</span><item.icon size={23}/></div><h3>{item.title}</h3><p>{item.text}</p></article></Reveal>)}</div></section>
 <section className="hz-learning" id="aprendizado"><div className="hz-container"><Reveal className="hz-section-head"><div><Eyebrow number="02">O QUE VOCÊ VAI APRENDER</Eyebrow><h2>Conhecimento que<br/><span>encontra a vida real.</span></h2></div><p>Da primeira impressão ao atendimento.<br/>Do contato ao acompanhamento dos resultados.</p></Reveal><div className="hz-learning-layout"><div className="hz-learning-aside"><p>Não é sobre fazer tudo.{' '}<br/>É sobre entender{' '}<br/><strong>o que faz sentido{' '}<br/>para você.</strong></p><a href="#inscricao" className="hz-round-link" aria-label="Conhecer o projeto"><ArrowUpRight size={27}/></a><span>SEU NEGÓCIO. SUA REALIDADE.</span></div><Accordion type="single" collapsible defaultValue="topic-01" className="hz-topics">{applications.map(a=><AccordionItem value={'topic-'+a.number} key={a.number}><AccordionTrigger><span className="hz-topic-number">{a.number}</span><span>{a.title}</span></AccordionTrigger><AccordionContent><p>{a.description}</p><div className="hz-topic-delivery"><Check size={17}/><span>{a.delivery}</span></div></AccordionContent></AccordionItem>)}</Accordion></div></div></section>
 <section className="hz-manifesto"><div className="hz-container"><Eyebrow>ALÉM DA TÉCNICA</Eyebrow><Reveal><h2>Sua profissão começa<br/>na técnica.<br/><span>Mas não termina nela.</span></h2></Reveal><div className="hz-manifesto-bottom"><p>Você continua especialista na sua profissão.<br/>E aprende a fazer seu trabalho chegar às pessoas.</p><Action href={offer.checkoutUrl} onClick={checkoutClick}>Quero assinar</Action></div></div></section>
 <section className="hz-container hz-section hz-enrollment" id="inscricao"><Reveal><Eyebrow number="03">PARA O SEU PRÓXIMO CAPÍTULO</Eyebrow><h2>Mais intenção.<br/><span>Em cada oportunidade.</span></h2><p>Para profissionais que querem divulgar o trabalho com clareza, melhorar o atendimento e acompanhar o que realmente funciona.</p><p className="hz-fine">O aprendizado pede aplicação. Os resultados dependem do serviço, do público e do contexto de cada negócio.</p></Reveal><Reveal><div className="hz-access-card"><div className="hz-access-heading"><Brand/><span>APRENDER + APLICAR</span></div><h3>Marketing que cabe<br/>na sua realidade.</h3><ul>{['Acesso imediato às aulas já gravadas','Uma nova aula completa por semana','Exemplos e atividades para aplicar no seu negócio','Presença digital, atendimento e resultados'].map(t=><li key={t}><Check size={17}/>{t}</li>)}</ul><div className="hz-price"><strong>R$37</strong><span>/mês</span></div><span className="hz-billing-note">Assinatura mensal</span><a className="hz-action hz-enroll" href={offer.checkoutUrl} onClick={checkoutClick}>Quero assinar<ArrowUpRight size={18}/></a><p>Após a confirmação do pagamento, acesse as aulas já gravadas. Uma nova aula completa é liberada por semana.</p></div></Reveal></section>
 <section className="hz-faq" id="duvidas"><div className="hz-container hz-faq-grid"><div><Eyebrow number="04">AINDA TEM ALGUMA DÚVIDA?</Eyebrow><h2>Vamos<br/><span>conversar.</span></h2></div><Accordion type="single" collapsible className="hz-faq-list">{faqs.map(([q,a],i)=><AccordionItem value={'faq-'+i} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>
 </main><footer className="hz-footer hz-container"><div className="hz-footer-top"><Brand/><p>Aprender hoje.<br/>Construir o que vem depois.</p><a href="#inicio" className="hz-round-link" aria-label="Voltar ao início"><ArrowUpRight size={24}/></a></div><div className="hz-footer-bottom"><span>© 2026 Além da Técnica</span>{offer.termsUrl&&<a href={offer.termsUrl}>Termos</a>}{offer.privacyUrl&&<a href={offer.privacyUrl}>Privacidade</a>}{offer.supportUrl&&<a href={offer.supportUrl}>Contato</a>}</div></footer></div></TooltipProvider>;
}
